### ISSUE TITLE
animsition not executing

### ISSUE THREAD

**Issue by wadie** [blivesta/animsition#107]
Have included the required scripts and have this simply HTML markup

`<div class="animsition-overlay" data-animsition-overlay="true">
<a href="ok.php" class="animsition-link"></a>
<a href="yay.php" class="animsition-link"></a>
</div>`

This is my js,pretty much copied it from the tut

`$(document).ready(function() {
    $(".animsition-overlay").animsition({
    inClass: 'overlay-slide-in-right',
    outClass: 'overlay-slide-out-right',
    inDuration: 1500,
    outDuration: 800,
    //linkElement: '.animsition-link',
    linkElement: 'a:not([target="_blank"]):not([href^="#"])'
    loading: false,
    loadingParentElement: 'body', //animsition wrapper element
    loadingClass: 'animsition-loading',
    loadingInner: '<img src="../css/img/load.gif" />', // e.g '<img src="loading.svg" />'
    timeout: false,
    timeoutCountdown: 5000,
    onLoadEvent: false,
    browser: [ 'animation-duration', '-webkit-animation-duration'],
    // "browser" option allows you to disable the "animsition" in case the css property in the array is not supported by your browser.
    // The default setting is to disable the "animsition" in a browser that does not support "animation-duration".
    overlay : false,
    overlayClass : 'animsition-overlay-slide',
    overlayParentElement : 'body',
    transition: function(url){ window.location.href = url; }
  });
});`

Any input would be appreciated! <3

**Comment by danieljuiche** [comment]
Hey what version of the jQuery are you using? For some reason it doesn't seem to work for me either with jQuery Core 3.1.0

Try using older version like jQuery Core 2.2.4 or something if that's the case
