### ISSUE TITLE
Animsition doesn't work with jQuery 3.2.1

### ISSUE THREAD

**Issue by kilimanjjjaro** [blivesta/animsition#133]
Hi,

Animsition is not working with the latest version of jQuery. Its work fine with 1.11.0 version.

Any fix? I don't want use an older version of jQuery 😕

**Comment by kilimanjjjaro** [comment]
Yes, before to post this, I check that temporary fix but it does not work with the latest version of jQuery (3.2.1).

**Comment by kilimanjjjaro** [comment]
Yes, I tried and work fine with v3.1.1 but it does not work with v3.2.1.

Anyway, thanks @makshh 😀. I just did the same animation with CSS3 and a few JavaScript lines.

**Comment by mabdelfattah** [comment]
@gonzaloemanuelcastillo can you please share how did you do that?

**Comment by neckarpixel** [comment]
Hey, I've tried multiple v3.* versions of jQuery, no success.
When I switch back to v2.2.4 Animsition works fine.
Testet on Chrome 62 and Firefox 57 on macOS 10.13.1

**Comment by rfontanella** [comment]
It doesn't work for me too. Tested on Chrome, Explorer, Firefox on Windows 8.1 Pro

**Comment by neckarpixel** [comment]
Horray!
Animsition with jQuery 3.3.1 is working.

EDIT: hm.. not every time... strange behaviour in my project, maybe other users will have more luck than me...

**Comment by toto011** [comment]
> Horray!

Horray!!

**Comment by itsHall** [comment]
Unfortunately I had to move on from Animsition after the jQuery conflicts.

**Comment by dlewand691** [comment]
No luck here, still doesn't work. May have to try another like swuup
