### ISSUE TITLE
Loading problems and iOS Safari back button issue

### ISSUE THREAD

**Issue by ghost** [blivesta/animsition#16]
In Safari on iOS when you click the back button to go to the previous page the page appears blank. Also some pages don't load at all. The loading icon never disappears. You have to refresh for the page to load.

**Comment by jackyon** [comment]
hm... I really love this plugin, but seems the back button still not been fixed yet. On the android device, still have back blank issue.

**Comment by jackyon** [comment]
today I found this issue also happened in ios safari. This issue happened when you special the animation, like: data-animsition-out="fade-out-left".  Then when click the back button in ios safari, it will return blank.
