### ISSUE TITLE
Displays the old page twice

### ISSUE THREAD

**Issue by ghost** [blivesta/animsition#19]
Hi there, 

i would love to use this great plugin for a drupal installation. The transition itself works fine but the old page displays twice. After one click, the animation begins. After fading out the old content, the page displays again followed by the url request. The new page loads followed by the choosen transition.
Are there ways to solve this?

Thank you very much

**Comment by senkmathew** [comment]
Hi
Sir, Could you please tell me how this can be used in div transition. I want to keep the header and footer only the central div should move. Is this possible with this.
