### ISSUE TITLE
can install / use it 

### ISSUE THREAD

**Issue by Nugrah** [blivesta/animsition#21]
hi, nice to see you project, but can i ask something, i have download your animsition, but can i know how to use it for default html, because after i download it i try to see the docs package but is not appear, can i get any solutions?

**Comment by gussiglo21** [comment]
HI Blivesta

I liked your project and I started trying to experiment witn simple page  using the effects of Animsition.
I followed the instructions but it dont works.
The page stills showing none, only the white background.
I copied all folders (dist, docs and src to the folder ANIMSITION) but it dont works.
Which is the problem? Please help
Thank you

The HTML code of the test page is:

<!DOCTYPE html>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>TEST PAGE</title>
</head>

<body>

<div class="animsition">
	<a href="page1.html" class="animsition-link" data-animsition-out="zoom-out" data-animsition-out-duration="2000">
	animsition link 1</a>
	<a href="page2.html" class="animsition-link" data-animsition-out="zoom-out" data-animsition-out-duration="500">
	animsition link 2</a></div>
	

<link rel="stylesheet" href="ANIMSITION/dist/css/animsition.min.css">

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<script src="ANIMSITION/dist/js/jquery.animsition.min.js"></script>
<script type="text/javascript">
 $(document).ready(function() {
  
  $(".animsition").animsition();
});
  </script>

</body>

</html>

**Comment by gussiglo21** [comment]
I solved I solved I solved it!!!!!!!!!! :)
I downloaded jquery.min.js and it is working in a folder!
It dont works on src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
Ready! I'm happy! 
Thank you anyway!

**Comment by Eggotron** [comment]
To work on source you have to add: https: 



—
Enviado desde Mailbox

**Comment by gussiglo21** [comment]
Thank you SirYou're right.Yesterday I forgotten that ruleThank you again!

      De: Jorge Enrique Peña Lama <notifications@github.com>
 Para: blivesta/animsition <animsition@noreply.github.com> 
CC: gussiglo21 <gustavosainz@yahoo.com.ar> 
 Enviado: Jueves, 26 de marzo, 2015 3:02:40
 Asunto: Re: [animsition] can install / use it (#21)
   
To work on source you have to add: https: 



—
Enviado desde Mailbox
