### ISSUE TITLE
Apply animsition on certain pages

### ISSUE THREAD

**Issue by Rachel-AK** [blivesta/animsition#22]
Hello, Is it possible to apply animsition on certain pages and not on all the pages of the website?

**Comment by gauravpadia** [comment]
@Rachel-AK You have to apply your own logic for this. Just not include the script and don't add animsition classes to elements on the page you don't want to apply animation. I hope this makes sense. Thanks.

**Comment by Rachel-AK** [comment]
Thank you, that's what i did. I was just making sure i wasn't missing anything.
