### ISSUE TITLE
middle mouse button

### ISSUE THREAD

**Issue by sleeman** [blivesta/animsition#24]
How to disable animsition at the middle mouse button ?!! if i am using animsition at the whole page i cant open new tab using the middle button !!!

**Comment by sleeman** [comment]
Actually this happen only in webkit browser , in firsfox and IE middle mouse button open new tab !!

**Comment by ungki** [comment]
Are you using `.animsition-link` on whole page? such as:

``` html
<a href=".../" class="animsition-link"></a>
```

If you use the <a> markup, I guess, must not for the present. linkElement is a just option, using the link for different animation effect.

``` javascript
linkElement           :   '.animsition-link', 
```  

You can markup this but linkElement. 

``` html
<a href=".../">link</a>
or 
<a href=".../" target="_blank">link</a>
```

need diff effect?

**Comment by sleeman** [comment]
No i didnt add any animsition-link class to a tag , i am just wrapping my page with:

<pre> <div class ="animsition"></div> </pre>

<pre> 

// linkElement           :   '.animsition-link', 
 linkElement   :   'a:not([target="_blank"]):not([href^=#])'
</pre>

If you can try it please at the demo page , click any effect with middle button  it will not open you new tab , using any webkit browser ..

**Comment by sleeman** [comment]
No i  didn't use  animsition-link class i am just wrapping my page with div class animsition..

and :
// linkElement           :   '.animsition-link', 
linkElement   :   'a:not([target="_blank"]):not([href^=#])..

If you  try it  with demo page , click at any effect with middle button it will not open new tab !! it behave like left button !! use any webkit browser ..

**Comment by ungki** [comment]
I've clicked with middle button in demo page. It's not working by `linkElement`. It's a obviously bug. However, for now, if you need not different effect per link, you can remove linkElement. I think need not.

```
// linkElement   :   'a:not([target="_blank"]):not([href^=#])'
```

**Comment by sleeman** [comment]
Yes this solve it for now , but losing the outClass effect .. 

Thanks for help...

**Comment by vburlak** [comment]
@sleeman did you found solution for this problem?

i'm trying to use animsition at the same configuration: 
1. added `.animsition` class to `body` element and 
2. used `linkElement   		  :   'a:not([target="_blank"]):not([href^=#])',`

Make some tests:
Conclusion:
* All webkit browsers (Google Chrome, Safari, Opera) — `Middle Mouse Click` and `cmd/ctrl + left button click`(middle button alternative for trackpad), don't open new tab. reloading page in same 
tab.
* Mozilla Firefox in OSX - `middle button click` works, but `cmd/ctrl + left button click` don't work.

**Comment by ungki** [comment]
@vburlak How about it?

1. not use linkElement:
    // linkElement: '',

2. add this source in your other scripts.js file:

``` javascript
$("a:not([target="_blank"]):not([href^=#])").click(function(e) {
  e.preventDefault();
});
```

**Comment by vburlak** [comment]
@ungki thx, for reply...
ok, i'm almost deleted `// linkElement: '',` from my script.. 
And now animsition using `linkElement: ".animsition-link",` which defined as plugins default param. Then I must add `.animsition-link` class to all links on all pages — what's is not perfect solution :)
So, i think, it's loosing `outClass` effect — because animsition works only on document ready in that case. When we clicking on link without class `.animsition-link` — we loosing outClass, because we don't clicking correct DOM element with necessary class.

I put together events to recognize that was produced Middle Mouse click or ctrl/cmd + click:

```
$('a:not([target="_blank"]):not([href^=#])').click(function(e){
	var href = $(this).attr('href');
	// check if clicked middle mouse button
	// check if user clicked with command key (for mac) or ctrl key (for windows)
	if(e.which === 2 || e.metaKey || (navigator.platform.toUpperCase().indexOf('WIN')!==-1 && e.ctrlKey)) {
	    window.open(href,'_blank');
	}
});
```
It's open link in new window, but this also shows outClass effect and opens clicked permalink in same window.. 
I will try to make a hook in animsition.js for exlude middle button event and ctrl/cmd + click tomorrow..

**Comment by sleeman** [comment]
@vburlak thx for participate , No i didn't came up with any good solution , i write something similar to your event  to recognize Middle Mouse when click , its give me the same result you have !! 
Let us know please if you came to any solution  tomorrow ...

**Comment by vburlak** [comment]
ok, guys, I just added shift + click event (open new browser window) d9b9629da72ccd4dd4bef972155cb6af0a25c318 and created pull request..

I can't check that fix in Win browsers now, so need your help with testing.

I must say a few nuances:
* in Firefox on OSX new tab opened not in background when used `cmd + click` event. 
* in Safari on OSX new tab opened not in background when opened via `middle button click`

I'm searched quick fix, but can't find anything usable..

**Comment by sleeman** [comment]
Tested on windows 8 in IE11  work fine , In Google Chrome work fine .In Firefox work fine .

Good work @vburlak , Thank you...

**Comment by ungki** [comment]
```
linkElement : '.animsition-link',
linkElement : 'a:not([target="_blank"]):not([href^=#])',
```

I've tested on win7. `middle mouse click` and `ctrl + click` are going well.

- IE7+ :)
- chrome
- firefox
- opera
- safari

and on linux (fedora) `middle mouse click` fine. `ctrl + click` not working. but `ctrl + shift + click` great.

- chrome
- firefox 

@vburlak Cool :+1:

**Comment by vburlak** [comment]
@sleeman @ungki very good :)
