### ISSUE TITLE
Animations stuck in Safari 8.0.3 ?

### ISSUE THREAD

**Issue by brainra** [blivesta/animsition#25]
Hi there

When opening the animsition demo page on safari 8.0.3, the loading animation works, but the page afterwards appears blank. There seems to be a problem with animations and Safari, is there a fix ?

**Comment by jackyon** [comment]
why close? this issue happened same to me. any solution?

**Comment by brainra** [comment]
It was a problem related to Yosemite. I rebooted my macbook and it worked again. My Safari was glitched
