### ISSUE TITLE
Please correct path directories in bower files 

### ISSUE THREAD

**Issue by S3ak** [blivesta/animsition#26]
#Wrong references in main property

currently you have 
    "main": [
    	"dist/css/animsition.css",
    	"dist/css/animsition.min.css",
    	"dist/js/animsition.js",
    	"dist/js/animsition.min.js"
    ],

should be 
    "main": [
    	"dist/css/animsition.css",
    	"dist/css/animsition.min.css",
    	"dist/js/jquery.animsition.js",
    	"dist/js/jquery.animsition.min.js"
    ],

**Comment by blivesta** [comment]
Thanks! f18f7d8
