### ISSUE TITLE
Start animsition when i want

### ISSUE THREAD

**Issue by simox-dev** [blivesta/animsition#33]
Hi!!
I'm start to use animsition a few day ago and is really nice!
I have a problem, can I start the animsition when I want and not only on "(document).ready" ??

I want to call the animsition when I'm in a special zone of the view.

Thanks

**Comment by ungki** [comment]
add animsition.js & call & html markup in your custom page only. or async?

https://github.com/filamentgroup/loadJS
https://github.com/jrburke/requirejs

**Comment by stailer** [comment]
My solution : https://github.com/blivesta/animsition/issues/46

**Comment by men232** [comment]
Basic example

```js
$('body').on('click', function(event) {
	$('.animsition').animsition('pageOut', $(event.target), 'myURL');
});
```js

**Comment by blivesta** [comment]
@men232 :+1:
