### ISSUE TITLE
Trigger animsition from javascript

### ISSUE THREAD

**Issue by michaelryancaputo** [blivesta/animsition#34]
Great plugin and it's working well, btu there are a few places that i'd like to trigger the page transition event from javascript (drop down select menus).

I can't seem to find a way to trigger the event to fire through javascript, am I missing something?

**Comment by michaelryancaputo** [comment]
It appears the only way to do it is by adding a class to your parent element. Can someone confirm this for me?

**Comment by blivesta** [comment]
Provide a test case please.

**Comment by stailer** [comment]
My solution : https://github.com/blivesta/animsition/issues/46
