### ISSUE TITLE
Opacity isn't triggered

### ISSUE THREAD

**Issue by seppentoni** [blivesta/animsition#38]
Hi.

I try to use animsition.

The loading screen appears (and looks nice) but the opacity of ```.animsition``` doesn't change to ```1```. Why is that?
I have no console errors no other animations in place. When I set opacity to 1 everything looks fine.

And If I set opacity to 1 via devtools and try to click a link with ```class="animsition-link"``` nothing happens. Does this need a specifc jquery version or what else could it be? Strange that I get no error whatsoever in devtools (OSX Chrome latest).

**Comment by seppentoni** [comment]
Okay. Circling the problem. If I add the animsitron css it works. If I use the .less file it doesn't. Although it seems to import everything from the less file properly.

**Comment by BillKarkavos** [comment]
just a suggestion - for me the issue was this

add https:
to this

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

so it is
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
