### ISSUE TITLE
Working with Animsition and Infinite Scroll js

### ISSUE THREAD

**Issue by DhrubaRC** [blivesta/animsition#39]
Hello,

I am using infinite scroll js (with behaviour set to twitter) to load in new contents on the index page. My concern is, how do I re-initiate <code>animistion</code> on the new posts that are being loaded via infinite scroll? I have described in detail the page structure being followed and would appreciate it very much if anyone can kindly share a solution for the same.

<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
  &lt;head&gt;&lt;/head&gt;
  &lt;body&gt;
    &lt;div class="animsition"&gt;
      &lt;header class="header"&gt;&lt;/header&gt;
      &lt;main class="main"&gt;
        &lt;section class="main-body"&gt;
          &lt;div id="infinite-scroll"&gt;
            &lt;article class="post"&gt;
               &lt;div class="post-body"&gt;
                  &lt;h2 class="post-title"&gt;
                  	&lt;a href="" class="nav-link" title=""&gt;&lt;/a&gt;
                  &lt;h2&gt;
               &lt;/div&gt;
            &lt;/article&gt;
          &lt;/div&gt;
          &lt;div class="pagination"&gt;
            &lt;a href="" class="next"&gt;Load Older Items&lt;/a&gt;
          &lt;/div&gt;
        &lt;/section&gt;
      &lt;/main&gt;
      &lt;footer class="footer"&gt;&lt;/footer&gt;  
    &lt;/div&gt;
  &lt;/body&gt;
&lt;/html&gt;
</code>
</pre>

And here is the JS,

<pre>
<code>
$(".animsition").animsition({
  inClass               :   'fade-in',
  outClass              :   'fade-out',
  linkElement           :   '.nav-link',
  overlay               :   false
});
$(function() {
  $("#infinite-scroll").infinitescroll({ 
    navSelector: ".pagination",
    nextSelector: ".next",
    itemSelector: ".post",
    behavior: "twitter"
  },
  function(newElements){
    
  });
</code>
</pre>

**Comment by nvartolomei** [comment]
I have the same problem, it is because event handler is attached to elements on initial page load.

**Comment by southerneer** [comment]
Just posted [an answer to this problem](http://stackoverflow.com/a/31616248/476228) on StackOverflow.

**Comment by blivesta** [comment]
@southerneer :+1: 
https://github.com/blivesta/animsition/blob/master/dist/js/animsition.js#L109
