### ISSUE TITLE
Firefox back button issue

### ISSUE THREAD

**Issue by gauravpadia** [blivesta/animsition#4]
Hello @blivesta 

In firefox when you click back button to go to previous page then page becomes blank. 

To reproduce this issue open your demo http://git.blivesta.com/clickstream/ in firefox and click any other link and then click browser back button you will see that page becomes blank. This is because firefox does not trigger document ready on back button.

To fix this please add an empty unload window event somewhere in your script, something like:

``` javascript
window.onunload = function() {};
```

Please see this link http://stackoverflow.com/questions/2638292/after-travelling-back-in-firefox-history-javascript-wont-run

**Comment by jackyon** [comment]
not working on android 4.4.4
