### ISSUE TITLE
How to apply transition only into a specific html block?

### ISSUE THREAD

**Issue by hugohcn** [blivesta/animsition#43]
Hello guys,

First of all, thank you all for the good script.

I have 3 process pages (like a wizard) and I need to apply the page transitions inside the container element of the pages (header and footer should not flash with the postback - Like a master page).

Could you help me? I got apply the effects, however the header and footer are flashing :(

Thanks!

**Comment by hugohcn** [comment]
Problem solved.

**Comment by blivesta** [comment]
:beer:
