### ISSUE TITLE
Animsition does not support this browser

### ISSUE THREAD

**Issue by tino415** [blivesta/animsition#44]
All online demos was working, but when I install it on localhost, i get this message.

**Comment by dsaronin** [comment]
I get the same error using latest stable version of Chrome Version 43.0.2357.65 (64-bit) and a fresh install of animsition.

**Comment by ngergo6** [comment]
I get the same error.

The online demos are working fine but when I try the supplied code from the bottom of the page it says that my browser is not supported.
I tried it with the latest stable version of Chrome, Firefox and Internet Explorer. I also had the latest (3.5.2) version of Animsition that I downloaded from Bower.

My html looks something like this:
```
<head>
    ....
    <link rel="stylesheet" href="./mycssfolder/animsition.min.css" ></link>
    ....
</head>
<body>
    <a href="./myotherpage.html">Test</a>
    ....
    <script src="./myscriptfolder/jquery.min.js"></script>
    <script src="./myscriptfolder/animsition.min.js"></script>
    <script>
        $(function (){
            // config from the demo site copied here
        });
    </script>
</body>
```

Any help would be much appreciated

**Comment by dsaronin** [comment]
I found a work-around but even after that I couldn't get animstration to work (the page just hung forever in a 'loading' state). I gave up and went with jquery.smoothState.js which works fine and I got working in about 30 minutes.

The animsition work-around: change unSupportCss in the config options to '[ ]' (see below),
```
$(document).ready(function() {
    $(".animsition").animsition({
      inClass               :   'fade-in',
    outClass              :   'fade-out',
    inDuration            :    1500,
    outDuration           :    800,
    linkElement           :   '.animsition-link',
    // e.g. linkElement   :   'a:not([target="_blank"]):not([href^=#])'
    loading               :    true,
    loadingParentElement  :   'body', //animsition wrapper element
    loadingClass          :   'animsition-loading',
    unSupportCss          : [     ],
    //"unSupportCss" option allows you to disable the "animsition" in case the css property in the array is not supported by your browser.
    //The default setting is to disable the "animsition" in a browser that does not support "animation-duration".
    overlay               :   false,
    overlayClass          :   'animsition-overlay-slide',
    overlayParentElement  :   'body'
  });
});
```

**Comment by blivesta** [comment]
it work in Chrome (v43.0.2357.81).

```html
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/css/animsition.css" ></link>
</head>
<body>


<div class="animsition">
  <a href="./myotherpage.html" class="animsition-link">Test</a>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/js/jquery.animsition.min.js"></script>
<script>
$(document).ready(function() {
  $(".animsition").animsition();
});
</script>

</body>
```

**Comment by KamesCG** [comment]
I am also receiving errors using Chrome version Version 43.0.2357.81 (64-bit)

![screen shot 2015-06-03 at 10 34 26 am](https://cloud.githubusercontent.com/assets/3408362/7966979/31a61a32-09dc-11e5-9b69-36d1a5648734.jpg)

**Comment by HarrisRobin** [comment]
+1

**Comment by mrpnkt** [comment]
+1 Chrome Version 45.0.2454.3 canary (64-bit)
works with @dsaronin workaround:
```
unSupportCss          : [     ],
```

**Comment by blivesta** [comment]
Updated to v4.0.0.
example:
https://github.com/blivesta/animsition/blob/master/sandbox/methods-in.html
https://github.com/blivesta/animsition/blob/master/sandbox/methods-out.html

**Comment by wyzssw** [comment]
+1
