### ISSUE TITLE
Adding a maximum loading time ?

### ISSUE THREAD

**Issue by ProgressionStudios** [blivesta/animsition#52]
It would be great to have an option to add a maximum loading time. That way users don't get stuck looking at a loading screen.

**Comment by ungki** [comment]
Good point. :+1:  

This is a next version. just simple... 
[animsition v4.0.0-alpha.0] (https://gist.github.com/blivesta/b1a01c2a4d39bf1ea628)
``` javascript
options = $.extend({
    loadingCleanTime : 500,
    ...


addLoading: function(){
    ...
    $loadingTarget.append(loading).removeClass().hide(options.loadingCleanTime);
    },
```

**Comment by spartan89** [comment]
yes that wood be awesome, please provide this option ..

**Comment by blivesta** [comment]
- Added `timeout` option.
- Added `timeoutCountdown` option.
https://github.com/blivesta/animsition/blob/master/dist/js/animsition.js#L33-L34
