### ISSUE TITLE
How to make Animsition work with window.location

### ISSUE THREAD

**Issue by owarigit** [blivesta/animsition#53]
Hi,

I'm trying to use animsition in my simple touchscreen app (web based). For some reason, we don't want the url displayed in status bar when the link hovered, so I try to use onclick. The problem is when I clicked the link, sometimes it redirected to undefined page (around 7 of 10). It work nicely while using href. Example : 

<a onClick="javascript: window.location = 'about.php';" class="animsition-link" data-animsition-out="fade-out-left">My Link</a>

Is there any suggestion for this?

Thanks

**Comment by blivesta** [comment]
Example 
https://github.com/blivesta/animsition/blob/master/sandbox/methods-out.html#L48-L53
