### ISSUE TITLE
Support for no-js

### ISSUE THREAD

**Issue by alioso** [blivesta/animsition#63]
Hey there, nice work! I think you should provide support for browsers with JS disabled. Otherwise you just end up stuck with 0 opacity. Maybe adding a js body class and use it as a prefix for .animsition ?

**Comment by blivesta** [comment]
The default setting is destroyed the `animsition` in the case of a browser this property does not work.
`animation-duration` (IE10+)
https://github.com/blivesta/animsition/blob/master/src/js/animsition.js#L29
