### ISSUE TITLE
How to get loadingClass to work

### ISSUE THREAD

**Issue by ihabovich** [blivesta/animsition#65]
Hello,
I am just get down many trials to make loadingClass work(show the loading circle and :after content text). Should I place Div with loadingClass name somewhere?

**Comment by Mogeek** [comment]
Hello,

I have the same issue. Aside from setting the "loading" option to "true" in the script is there anything else that needs to be done?

**Comment by ihabovich** [comment]
@Mogeek I just got it to work. Just place `<div class="animsition-loading"></div>` before the end of your body `</body>`, where `animsition-loading` is the default loadingClass assigned in options.

**Comment by shawnprimal** [comment]
I have placed the loading div "<div class="animsition-loading"></div>" in the bottom of the site, just above the body tag outside of the wrapper.  I am still not seeing the loading icon when I transition pages it only shows on the first load.  Any help here would be great.

**Comment by shawnprimal** [comment]
Also the wordpress plugin is doing the same thing.
