### ISSUE TITLE
Animsition and Wow Js

### ISSUE THREAD

**Issue by Gilles73** [blivesta/animsition#68]
Hi everybody, I’m french Graphic/UX designer and new member on Github.
I’ve created a new version of my website to present a selection of my works but I have two problems with the final version.
www.gillesnolorgues.com

First problem:
To sum up, I use the Animsition plugin to start the CSS fade transition between pages and when I scroll, I use the Wow plugin and Animate CSS to start the CSS fadeup on my pictures. 

My problem, when the page is loaded for the first time, the CSS fadeup have already started. It works perfectly when the page has already been loaded.
May be, is it a problem with the JS code? I don’t find the solution.

Second problem:
It’s about the image hover effects on iOS, I have to tape twice on the screen to start the image link and I would like to tape one.

Many thanks in advance for your assistance.

**Comment by diegoviola1** [comment]
Hi, try to initialize wow.js after the "inStart" event of animsition.

     $(".animsition").animsition();
     $(".animsition").on('animsition.inStart', function(){
        new WOW().init();
      })

**Comment by blivesta** [comment]
@diegoviola1 Thanks!
