### ISSUE TITLE
Allow targeting "_blank" windows for external links

### ISSUE THREAD

**Issue by dlewand691** [blivesta/animsition#75]
When adding target="_blank" to links, they don't open in a new window as expected. Is there a solution to allow this?

**Comment by gauravpadia** [comment]
Hi @dlewand691 

You can exclude certain a tags by setting linkElement option to something like ``linkElement: 'a:not([target="_blank"]):not([href^=#])'``

See step 3 on demo link - http://git.blivesta.com/animsition/

Thanks.
