### ISSUE TITLE
Flash between page loads -> Chrome & Safari

### ISSUE THREAD

**Issue by drnen101** [blivesta/animsition#76]
I've seen this mentioned in the issues section before but i cant see that there is actually an answer for it. I'm using the overlay effect to load between pages, however there is a flicker in between each page when viewing in chrome or safari. Firefox seems to load it fine. I noticed in the css package that many of the overlay transitions were missing -webkit- specific definitions so my assumption is that this must be in part to that. Can someone tell me why this is happening? Really ruins the overall experience when it isnt a fluid transition as intended

**Comment by drnen101** [comment]
any feedback on my issue?  really breaks the whole seamless animation between pages that is this plugin is all about

**Comment by blivesta** [comment]
See overlay demo on sandbox.
https://github.com/blivesta/animsition/blob/master/sandbox/overlay1.html#L10-L55

> missing -webkit- specific definitions....

Which is the rule? CSS vendor prefixes will have been added using the [autoprefixer](https://github.com/postcss/autoprefixer)

**Comment by eikeco** [comment]
I am having the same problem. If you background is black you see a white flash between the page change.

**Comment by drnen101** [comment]
If i add your files exactly as they are downloaded from here, and host them online I am seeing a flash between pages in chrome http://defyordie.com/animsition/sandbox/overlay1.html and in safari nothing happens at all. so what am i missing?  The demo on your site seems to work fine, so what is the disconnect on the example files in your sandbox?

**Comment by blivesta** [comment]
Fixed. Please take another look.
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sandbox: overlay1 - Animsition</title>
  <link href="sandbox.css" rel="stylesheet">
  <link href="../dist/css/animsition.min.css" rel="stylesheet">
  <style media="screen">
    .bg-init,
    .animsition-overlay-slide {
      background-color: #81D4FA;
    }
  </style>
</head>
<body class="bg-init">

  <div class="animsition-overlay">
    ...
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
  <script src="../dist/js/animsition.min.js" charset="utf-8"></script>
  <script>
  $(document).ready(function() {
    $('.animsition-overlay').animsition({
      inClass: 'overlay-slide-in-top',
      outClass: 'overlay-slide-out-top',
      overlay : true,
      overlayClass : 'animsition-overlay-slide',
      overlayParentElement : 'body'
    })
    .one('animsition.inStart',function(){
      $('body').removeClass('bg-init');
    });
  });
  </script>

</body>
</html>
```

**Comment by drnen101** [comment]
ah makes perfect sense. Works like a charm now :)  thanks!

**Comment by DavidScanu** [comment]
Thanks a lot. Works for me too.

**Comment by AverageBrick** [comment]
I don't understand how to install/use this, can someone please help me?

**Comment by Malenua** [comment]
Thanks a lot 👍
