### ISSUE TITLE
animsition in input type button

### ISSUE THREAD

**Issue by dimavricos** [blivesta/animsition#77]
Hi !!
is there a way to use animsition for inputs as a tags?
like:

 input type="button" value="Checkout" class="button-1 checkout-button animsition-link" onclick="setLocation('/checkout')" 

 
is there something i can do here:
transition: function (url) { window.location.href = url; } ?

Thanks!!

**Comment by dimavricos** [comment]
Hi!!

i found a solution if someone has the same problem. I edit the plugin js file and changed the url on click 

    $document.on('click.' + namespace, options.linkElement, function (event) {
                        event.preventDefault();
                        var $self = $(this);
                        console.log(options);
                        var target = $(event.target);
                        var url = null;
                        if (target.is("a")) {
                           url =  $self.attr('href');
                    } 
                        else if (target.is("input"))
                        {
                            var str = $self.attr('onclick').replace('/', '');
                            var find = "'";
                            var re = new RegExp(find, 'g'); 
                            var str1 = str.replace(re, '');
                            url = str1.match(/\(([^)]+)\)/)[1];
                        }

                       
                        // middle mouse button issue #24
                        // if(middle mouse button || command key || shift key || win control key)
                        if (event.which === 2 || event.metaKey || event.shiftKey || navigator.platform.toUpperCase().indexOf('WIN') !== -1 && event.ctrlKey) {
                            window.open(url, '_blank');
                        } else {
                            __.out.call(_this, $self, url);
                        }

                    });

**Comment by blivesta** [comment]
🍻
