### ISSUE TITLE
iOS navigate back white screen bug

### ISSUE THREAD

**Issue by nvartolomei** [blivesta/animsition#78]
Hello,

You still didn't fixed old iOS bug, for example if before navigating away fade-out animation is triggered (fade-out class is added to body) and you press back button the page remains faded out.

You need to fix `in` method to undo the changes it did in `out` method. For example remove `outClass`. I quick and dirty fixed it by adding a call to `.removeClass('fade-out')` in `in` method.

Let me know if you need more details on this.

**Comment by llos** [comment]
+1

**Comment by blivesta** [comment]
It was fixed at the branch v4.0.1.
Please Take Another Look.
https://github.com/blivesta/animsition/commit/352fc352e622907a10a7181f9503d9e6a454b9be


v4.0.1 demo
http://git.blivesta.com/staging/

**Comment by nvartolomei** [comment]
I don't like this fix! :see_no_evil: Why you should reload the page when you can just replay the *in* animation. Aka reverse the *out* animation.

**Comment by nvartolomei** [comment]
Let me give it a try. We'll be back with a pull request.
