### ISSUE TITLE
How to prevent certain "a href" from triggering the preloader animation?

### ISSUE THREAD

**Issue by Viriathus** [blivesta/animsition#79]
I'm using magnific-popup.js for an image gallery and when I click on an image to view it on the lightbox it keeps triggering the animsition preloader. Is there a way to prevent certain "a href" from triggering the preloader animation? This must be a basic thing but I still didn't understand how to do it. Thank you!

**Comment by diegoviola1** [comment]
You can use something like this:

    $(".animsition").animsition({
         linkElement: 'a:not([target="_blank"]):not([href^=#]):not([data-no-animsition])',
    });

Then you can use "data-no-animsition" on links that have not to be animated.

    <a href="#" data-no-animsition>Gallery Link</a>

**Comment by blivesta** [comment]
@diegoviola1 🍻

**Comment by Viriathus** [comment]
It worked thanks!

**Comment by reppon97** [comment]
@diegoviola1 you, sir, saved my life
