### ISSUE TITLE
Going back in Safari causes blank page

### ISSUE THREAD

**Issue by llos** [blivesta/animsition#80]
Hi,

If you go back with your Safari browser a blank page appears and content doesn't load. Any solution for this?

Thanks

**Comment by blivesta** [comment]
It was fixed at the branch v4.0.1.
Please Take Another Look.
https://github.com/blivesta/animsition/commit/352fc352e622907a10a7181f9503d9e6a454b9be

v4.0.1 demo
http://git.blivesta.com/staging/

#78

**Comment by llos** [comment]
Thank you for the fast solution @blivesta! Works like a charm :)
