### ISSUE TITLE
Can interact with transparent elements when loading

### ISSUE THREAD

**Issue by ryanlittle** [blivesta/animsition#89]
When the page is loading, it sets the animsition element to `opacity: 0`.

The issue I face is that those transparent elements, for instance links, show a pointer cursor and can be clicked before the page is loaded and displayed.

Perhaps the loadingClass element could be set to be the full page with an increased z-index to prevent this? Or adjust the visibility instead of the opacity?

**Comment by rplittle** [comment]
I did come up with a workaround for this though.

Instead of `loadingClass: 'animsition-loading'`, I created an element and put the original loadingClass inside of it.

    loadingClass: 'animsition-loading-outer',
    loadingInner: '<div class="animsition-loading"></div>'

Then, I added the CSS:

    .animsition-loading-outer {
      width: 100%;
      height: 100%;
      position: absolute;
      top: 0;
      left: 0;
      z-index: 1000;
    }
