### ISSUE TITLE
iOS (8.2 tested) Safari - Stuck between inStart and inEnd

### ISSUE THREAD

**Issue by ryanlittle** [blivesta/animsition#90]
I am running into issues on iOS, but no other browser that I've tested. I pretty much used the code from the "fade" demo. When debugging, I can see that it gets stuck somewhere between inStart and inEnd, and my element remains as follows: `<div class="animsition fade-in" style="-webkit-animation: 1500ms;">`, which keeps it transparent.

The only thing I can see that I added was an extra loadingInner element, but when I set `loading: false`, the error persists.

```
  $('.animsition').animsition({
    inClass: 'fade-in',
    outClass: 'fade-out',
    inDuration: 1500,
    outDuration: 800,
    linkElement: 'a:not([target="_blank"]):not([href^=#]):not([href^="mailto\\:"])',
    loading: true,
    loadingParentElement: 'body',
    loadingClass: 'animsition-loading-outer',
    loadingInner: '<div class="animsition-loading"></div>',
    timeout: false,
    timeoutCountdown: 5000,
    onLoadEvent: true,
    browser: [ 'animation-duration', '-webkit-animation-duration'],
    overlay : false,
    overlayClass : 'animsition-overlay-slide',
    overlayParentElement : 'body',
    transition: function(url){ window.location.href = url; }
  });
```

The demos load fine, and I'm not seeing any errors in my console. I've also disabled all other JS, so I'm not sure what might be going on here. I was wondering if anyone else has experienced this.

Meanwhile, I'll continue to debug...

**Comment by rplittle** [comment]
I was testing on iOS Simulator (running iOS 8.2), where I found an issue, although using my iPhone with iOS 9, I do not see an issue. Unfortunately, I do not have an actual device running an older version of iOS.

Regardless, there still seems to be a bit of inconsistency:

None of the demos from the latest version of this repo worked on iOS Simulator, but accessing the site http://git.blivesta.com/animsition/ - those animations work fine. Perhaps the website is running an older version of the plugin.
