### ISSUE TITLE
Links throwing errors with jQuery 1.12

### ISSUE THREAD

**Issue by notanothercliche** [blivesta/animsition#99]
When using jQuery 1.12, I'm getting the error

Uncaught Error: Syntax error, unrecognized expression: [href^=#]

In my confirguration, I'm using this

linkElement: 'a:not([target="_blank"]):not([href^=#])',

How can I edit this expression to work correctly in jQuery 1.12?

Thank you!

**Comment by blivesta** [comment]
`a:not([target="_blank"]):not([href^="#"])` #74 #88 #95

**Comment by notanothercliche** [comment]
THANK YOU!
